In [1]:
# Dependencies
import pandas as pd
from pathlib import Path

In [2]:
# Store filepath in a variable
file = Path("Resources/baton_streets.csv")

In [3]:
# Read our data file with the Pandas library
batonDF = pd.read_csv(file)
batonDF.head()

,STREET NAME ID,STREET NAME,STREET FULL NAME,POSTAL COMMUNITY,MUNICIPAL COMMUNITY
0,1400342,PRIVATE STREET,PRIVATE STREET,BATON ROUGE,BATON ROUGE
1,1,4TH,N 4TH ST,BATON ROUGE,BATON ROUGE
2,10,11TH,S 11TH ST,BATON ROUGE,BATON ROUGE
3,100,ADDINGTON,ADDINGTON AVE,BATON ROUGE,BATON ROUGE
4,1000,CHALFONT,W CHALFONT DR,BATON ROUGE,PARISH

In [5]:
# Set new index to STREET NAME
# use .set_index() to replace the default pandas index with the values of the STREET NAME Ccolumn
batonDF = batonDF.set_index("STREET NAME")
batonDF.head()

,STREET NAME ID,STREET FULL NAME,POSTAL COMMUNITY,MUNICIPAL COMMUNITY
STREET NAME,,,,
PRIVATE STREET,1400342,PRIVATE STREET,BATON ROUGE,BATON ROUGE
4TH,1,N 4TH ST,BATON ROUGE,BATON ROUGE
11TH,10,S 11TH ST,BATON ROUGE,BATON ROUGE
ADDINGTON,100,ADDINGTON AVE,BATON ROUGE,BATON ROUGE
CHALFONT,1000,W CHALFONT DR,BATON ROUGE,PARISH

In [8]:
# Get the data contained within the "ADDINGTON" row and the "STREET FULL NAME" column
# location - .loc and .iloc
    # loc - uses text references for the row (pandas index) and column
    # iloc - uses number references for the rows and column
# using loc
addington01 = batonDF.loc["ADDINGTON", "STREET FULL NAME"]

# using iloc - Addington - row index 3, col index 1 
addington02 = batonDF.iloc[3, 1]

print(f"Using loc: {addington01}")

print(f"Using iloc: {addington02}")

Using loc: ADDINGTON AVE
Using iloc: ADDINGTON AVE

In [9]:
# Get the first five rows of data and the columns from "STREET NAME ID" to "POSTAL COMMUNITY"
# The problem with using "STREET NAME" as the index is that the values are not unique so duplicates are returned
# If there are duplicates and loc is being used, Pandas will return an error

# use loc - hardcode the first 5 row names and first 3 columns of data into lists
    #.loc[[List of rows],[List of columns]]
baton02DF = batonDF.loc[["PRIVATE STREET", "4TH", "11TH", "ADDINGTON",
                             "CHALFONT"],["STREET NAME ID","STREET FULL NAME", "POSTAL COMMUNITY"]]

#baton02DF.head()

# Using iloc will not find duplicates since a numeric index is always unique
#stuff = ["a","b","c"]
#stuff[0]

    # use slicing with iloc to reference the first 5 rows
    # 0:5 - start at index 0 and go up to (not include) index 5
    # 0:3 - start at index 0 and go up to (not include) index 3
baton03DF = batonDF.iloc[0:5, 0:3]
baton03DF.head()
# Using iloc will not find duplicates since a numeric index is always unique

                STREET NAME ID STREET FULL NAME POSTAL COMMUNITY
STREET NAME
PRIVATE STREET         1400342   PRIVATE STREET      BATON ROUGE
4TH                          1         N 4TH ST      BATON ROUGE
11TH                        10        S 11TH ST      BATON ROUGE
ADDINGTON                  100    ADDINGTON AVE      BATON ROUGE
CHALFONT                  1000    W CHALFONT DR      BATON ROUGE

In [11]:
# Using loc to select all rows for the `STREET FULL NAME` and `POSTAL COMMUNITY` columns.
# use : to select all idnexes for rows or column
batonDF.loc[:,["STREET FULL NAME", "POSTAL COMMUNITY"]].head()

               STREET FULL NAME POSTAL COMMUNITY
STREET NAME
PRIVATE STREET   PRIVATE STREET      BATON ROUGE
4TH                    N 4TH ST      BATON ROUGE
11TH                  S 11TH ST      BATON ROUGE
ADDINGTON         ADDINGTON AVE      BATON ROUGE
CHALFONT          W CHALFONT DR      BATON ROUGE

In [8]:
# Using iloc to select all rows for the second and third columns.
# use : to select all indexes for rows or column
batonDF.iloc[:. 1:3].head()

               STREET FULL NAME POSTAL COMMUNITY
STREET NAME
PRIVATE STREET   PRIVATE STREET      BATON ROUGE
4TH                    N 4TH ST      BATON ROUGE
11TH                  S 11TH ST      BATON ROUGE
ADDINGTON         ADDINGTON AVE      BATON ROUGE
CHALFONT          W CHALFONT DR      BATON ROUGE

In [12]:
# The following logic test/conditional statement returns a series of boolean values
parishTest = batonDF["MUNICIPAL COMMUNITY"] == "PARISH"
parishTest.head()

STREET NAME
PRIVATE STREET    False
4TH               False
11TH              False
ADDINGTON         False
CHALFONT           True
Name: MUNICIPAL COMMUNITY, dtype: bool

In [16]:
# loc will allow for conditional statements to filter rows of data
# Using loc on the logic test above only returns rows where the result is True
prairievilleDF = batonDF.loc[batonDF["POSTAL COMMUNITY"] == "PRAIRIEVILLE"]
prairievilleDF.head()

,STREET NAME ID,STREET FULL NAME,POSTAL COMMUNITY,MUNICIPAL COMMUNITY
STREET NAME,,,,
ALLIGATOR BAYOU,16497,ALLIGATOR BAYOU RD,PRAIRIEVILLE,PARISH
BLUFF,16498,BLUFF RD,PRAIRIEVILLE,PARISH

In [17]:
# iloc will also allow for conditional statements to filter rows of data
# Using iloc on the logic test above only returns rows where the result is True
prairievilleDF = batonDF[batonDF.iloc[:,2] == "PRAIRIEVILLE"]
prairievilleDF.head()

,STREET NAME ID,STREET FULL NAME,POSTAL COMMUNITY,MUNICIPAL COMMUNITY
STREET NAME,,,,
ALLIGATOR BAYOU,16497,ALLIGATOR BAYOU RD,PRAIRIEVILLE,PARISH
BLUFF,16498,BLUFF RD,PRAIRIEVILLE,PARISH

In [20]:
# Multiple conditions can be set to narrow down or widen the filter
prairieOrJacksonDF = batonDF.loc[
    (batonDF["POSTAL COMMUNITY"] == "PRAIRIEVILLE") | (batonDF["POSTAL COMMUNITY"] == "JACKSON")
]
prairieOrJacksonDF.head()

,STREET NAME ID,STREET FULL NAME,POSTAL COMMUNITY,MUNICIPAL COMMUNITY
STREET NAME,,,,
TALMADGE,4772,TALMADGE DR,JACKSON,PARISH
TREAKLE,4911,TREAKLE DR,JACKSON,PARISH
DENNIS,1452,DENNIS CT,JACKSON,PARISH
ALLIGATOR BAYOU,16497,ALLIGATOR BAYOU RD,PRAIRIEVILLE,PARISH
BLUFF,16498,BLUFF RD,PRAIRIEVILLE,PARISH