In [4]:
# Dependencies
import pandas as pd
from pathlib import Path

In [5]:
# Load in file
# Store filepath in a variable
movie_file = Path("Resources/movie_scores.csv")

In [6]:
# Read and display the CSV with Pandas
movieDF = pd.read_csv(movie_file)
movieDF.head()

,FILM,RottenTomatoes,RottenTomatoes_User,Metacritic,Metacritic_User,IMDB,Fandango_Stars,Fandango_Ratingvalue,RT_norm,RT_user_norm,...,IMDB_norm,RT_norm_round,RT_user_norm_round,Metacritic_norm_round,Metacritic_user_norm_round,IMDB_norm_round,Metacritic_user_vote_count,IMDB_user_vote_count,Fandango_votes,Fandango_Difference
0,Avengers: Age of Ultron (2015),74,86,66,7.1,7.8,5.0,4.5,3.70,4.3,...,3.90,3.5,4.5,3.5,3.5,4.0,1330,271107,14846,0.5
1,Cinderella (2015),85,80,67,7.5,7.1,5.0,4.5,4.25,4.0,...,3.55,4.5,4.0,3.5,4.0,3.5,249,65709,12640,0.5
2,Ant-Man (2015),80,90,64,8.1,7.8,5.0,4.5,4.00,4.5,...,3.90,4.0,4.5,3.0,4.0,4.0,627,103660,12055,0.5
3,Do You Believe? (2015),18,84,22,4.7,5.4,5.0,4.5,0.90,4.2,...,2.70,1.0,4.0,1.0,2.5,2.5,31,3136,1793,0.5
4,Hot Tub Time Machine 2 (2015),14,28,29,3.4,5.1,3.5,3.0,0.70,1.4,...,2.55,0.5,1.5,1.5,1.5,2.5,88,19560,1021,0.5

In [7]:
# List all the columns in the table
# .columns to get the list
for col in movieDF.columns:
    print(col)

FILM
RottenTomatoes
RottenTomatoes_User
Metacritic
Metacritic_User
IMDB
Fandango_Stars
Fandango_Ratingvalue
RT_norm
RT_user_norm
Metacritic_norm
Metacritic_user_nom
IMDB_norm
RT_norm_round
RT_user_norm_round
Metacritic_norm_round
Metacritic_user_norm_round
IMDB_norm_round
Metacritic_user_vote_count
IMDB_user_vote_count
Fandango_votes
Fandango_Difference

In [8]:
# We only want IMDb data, so create a new table that takes the Film and all the columns relating to IMDB
columnList = ["FILM", "IMDB", "IMDB_norm", "IMDB_norm_round", "IMDB_user_vote_count"]
imdbDF = movieDF[columnList]
imdbDF.head()

,FILM,IMDB,IMDB_norm,IMDB_norm_round,IMDB_user_vote_count
0,Avengers: Age of Ultron (2015),7.8,3.90,4.0,271107
1,Cinderella (2015),7.1,3.55,3.5,65709
2,Ant-Man (2015),7.8,3.90,4.0,103660
3,Do You Believe? (2015),5.4,2.70,2.5,3136
4,Hot Tub Time Machine 2 (2015),5.1,2.55,2.5,19560

In [9]:
# We only like good movies, so find those that scored over 7, and ignore the norm rating
columnlist = ["FILM", "IMDB", "IMDB_user_vote_count"]
imdbDF = movieDF.loc[
    movieDF["IMDB"] > 7, columnList
]
imdbDF.head()

,FILM,IMDB,IMDB_norm,IMDB_norm_round,IMDB_user_vote_count
0,Avengers: Age of Ultron (2015),7.8,3.90,4.0,271107
1,Cinderella (2015),7.1,3.55,3.5,65709
2,Ant-Man (2015),7.8,3.90,4.0,103660
5,The Water Diviner (2015),7.2,3.60,3.5,39373
8,Shaun the Sheep Movie (2015),7.4,3.70,3.5,12227

In [11]:
# Find less popular movies--i.e., those with fewer than 20K votes
lessPopularDF = imdbDF.loc[
    imdbDF["IMDB_user_vote_count"] < 20000
]
lessPopularDF.head()

,FILM,IMDB,IMDB_norm,IMDB_norm_round,IMDB_user_vote_count
8,Shaun the Sheep Movie (2015),7.4,3.70,3.5,12227
9,Love & Mercy (2015),7.8,3.90,4.0,5367
10,Far From The Madding Crowd (2015),7.2,3.60,3.5,12129
20,"McFarland, USA (2015)",7.5,3.75,4.0,13769
29,The End of the Tour (2015),7.9,3.95,4.0,1320

In [12]:
# Finally, export this file to a spread so we can keep track of out new future watch list without the index
lessPopularDF.to_excel("movieWatchList.xlsx", index=False)

ModuleNotFoundError: No module named 'openpyxl'